POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "gg@gmail.com",
    "password": "gg"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "gg@gmail.com",
    "password": "gg"
}

###

POST http://localhost:3000/favorites/add
Content-Type: application/json

{
    "userId": "65e8c3c688019ed9bf2fd615",
    "productId": "1"
}